name: Run Playwright E2E Tests

on:
  workflow_dispatch: # Allows manual trigger, and also for dispatch from other workflows
    inputs:
      webapp_url:
        description: 'URL of the deployed web application to test'
        required: true
        default: 'http://localhost:3000' # Fallback for local testing or manual trigger
  push:
    branches:
      - main
    paths:
      - 'playwright-tests/**' # Trigger when changes occur in the playwright-tests directory
  pull_request:
    branches:
      - main
    paths:
      - 'playwright-tests/**'

env:
  WEBAPP_URL: ${{ github.event.inputs.webapp_url || 'http://localhost:3000' }} # Use input or default
  API_BASE_URL: ${{ github.event.inputs.api_url || 'http://localhost:8080/api' }} # Pass API URL as well if needed

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Playwright dependencies
        run: |
          cd playwright-tests
          npm install
          npx playwright install --with-deps # Install browser binaries and their system dependencies

      - name: Run Playwright Tests
        run: |
          cd playwright-tests
          npx playwright test --reporter=html,list,github
        env:
          WEBAPP_URL: ${{ env.WEBAPP_URL }}
          API_BASE_URL: ${{ env.API_BASE_URL }} # Pass to Playwright config/tests

      - name: Upload Playwright Test Report
        if: always() # Upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-tests/playwright-report
          retention-days: 5
